"""LAMMPS input script generator."""

from __future__ import annotations

import io
import textwrap
from dataclasses import dataclass, field
from typing import Literal

PotentialType = Literal["lj", "eam", "tersoff", "buckingham", "coulomb"]
EnsembleType = Literal["nvt", "npt", "nve", "nph"]
BoundaryType = Literal["p p p", "p p f", "p f p", "f p p", "p p s"]


@dataclass
class LAMMPSInput:
    """Configuration for generating a LAMMPS input script."""

    # System
    atoms_per_side: int = 10
    lattice_spacing: float = 5.26
    boundary: BoundaryType = "p p p"
    dimension: int = 3
    atom_style: str = "atomic"

    # Potential
    potential: PotentialType = "lj"
    epsilon: float = 1.0
    sigma: float = 1.0
    cutoff: float = 2.5

    # Minimization
    minimize: bool = True
    min_style: str = "cg"
    min_etol: float = 1.0e-4
    min_ftol: float = 1.0e-6
    min_maxiter: int = 10000
    min_maxeval: int = 100000

    # Dynamics
    ensemble: EnsembleType = "nvt"
    temperature: float = 300.0
    pressure: float = 0.0
    timestep: float = 0.002
    n_steps: int = 100000
    dump_freq: int = 1000
    thermo_freq: int = 100

    # Output
    dump_file: str = "dump.lammpstrj"
    thermo_file: str = "thermo.dat"
    restart_file: str = "restart.lammps"

    # Shear (optional)
    apply_shear: bool = False
    shear_rate: float = 0.001
    shear_direction: str = "xy"


def _build_header(cfg: LAMMPSInput) -> str:
    return textwrap.dedent(f"""\
        # SciMCP-generated LAMMPS input script
        # Generated by scimcp LAMMPS input generator
        #
        # System: {cfg.atoms_per_side}^3 atoms, a0={cfg.lattice_spacing}
        # Potential: {cfg.potential} (eps={cfg.epsilon}, sig={cfg.sigma}, rc={cfg.cutoff})
        # Ensemble: {cfg.ensemble}, T={cfg.temperature}, dt={cfg.timestep}
        # Steps: {cfg.n_steps}, dump every {cfg.dump_freq}

    """).encode("ascii", errors="replace").decode("ascii")


def _build_init(cfg: LAMMPSInput) -> str:
    lines = [
        "# --- Initialization ---",
        f"units           lj",
        f"dimension       {cfg.dimension}",
        f"boundary        {cfg.boundary}",
        f"atom_style      {cfg.atom_style}",
        "",
    ]
    return "\n".join(lines)


def _build_system(cfg: LAMMPSInput) -> str:
    lines = [
        "# --- System Setup ---",
        f"lattice         fcc {cfg.lattice_spacing}",
        f"region          box block 0 {cfg.atoms_per_side} 0 {cfg.atoms_per_side} 0 {cfg.atoms_per_side}",
        f"create_box      1 box",
        f"create_atoms    1 box",
        f"mass            1 1.0",
        "",
        "# --- Pair Potential ---",
    ]

    if cfg.potential == "lj":
        lines.append(f"pair_style      lj/cut {cfg.cutoff}")
        lines.append(f"pair_coeff      1 1 {cfg.epsilon} {cfg.sigma} {cfg.cutoff}")
    elif cfg.potential == "eam":
        lines.append("pair_style      eam/alloy")
        lines.append("pair_coeff      1 1 Cu.eam.alloy Cu")
    elif cfg.potential == "tersoff":
        lines.append("pair_style      tersoff")
        lines.append("pair_coeff      1 1 Si.tersoff Si")
    elif cfg.potential == "buckingham":
        lines.append(f"pair_style      buck/coul/long {cfg.cutoff}")
        lines.append(f"pair_coeff      1 1 1000.0 0.3 50.0")
    elif cfg.potential == "coulomb":
        lines.append(f"pair_style      coul/long {cfg.cutoff}")
        lines.append(f"pair_coeff      1 1 1.0")
        lines.append("kspace_style    pppm 1.0e-4")

    lines.append(f"neighbor        0.3 bin")
    lines.append(f"neigh_modify    delay 0 every 1 check yes")
    lines.append("")
    return "\n".join(lines)


def _build_minimize(cfg: LAMMPSInput) -> str:
    if not cfg.minimize:
        return ""
    lines = [
        "# --- Energy Minimization ---",
        f"thermo          {cfg.thermo_freq}",
        f"thermo_style    custom step temp pe ke etotal press vol",
        f"min_style       {cfg.min_style}",
        f"minimize        {cfg.min_etol} {cfg.min_ftol} {cfg.min_maxiter} {cfg.min_maxeval}",
        "",
    ]
    return "\n".join(lines)


def _build_dynamics(cfg: LAMMPSInput) -> str:
    lines = [
        "# --- Dynamics ---",
        f"timestep        {cfg.timestep}",
        f"thermo          {cfg.thermo_freq}",
        f"thermo_style    custom step temp pe ke etotal press vol lx ly lz",
        "",
    ]

    # Ensemble fix
    if cfg.ensemble == "nvt":
        lines.append(f"fix             1 all nvt temp {cfg.temperature} {cfg.temperature} 0.1")
    elif cfg.ensemble == "npt":
        lines.append(f"fix             1 all npt temp {cfg.temperature} {cfg.temperature} 0.1 iso {cfg.pressure} {cfg.pressure} 1.0")
    elif cfg.ensemble == "nve":
        lines.append(f"fix             1 all nve")
    elif cfg.ensemble == "nph":
        lines.append(f"fix             1 all nph iso {cfg.pressure} {cfg.pressure} 1.0")

    lines.append("")

    # Shear
    if cfg.apply_shear:
        rate = cfg.shear_rate
        if cfg.shear_direction == "xy":
            lines.append(f"fix             2 all deform 1 xy erate {rate} units box remap x")
        elif cfg.shear_direction == "xz":
            lines.append(f"fix             2 all deform 1 xz erate {rate} units box remap x")
        elif cfg.shear_direction == "yz":
            lines.append(f"fix             2 all deform 1 yz erate {rate} units box remap x")
        lines.append("")

    # Dump
    lines.extend([
        f"dump            1 all custom {cfg.dump_freq} {cfg.dump_file} id type x y z vx vy vz",
        f"dump_modify     1 sort id",
        "",
        "# --- Run ---",
        f"run             {cfg.n_steps}",
        "",
        "# --- Save Restart ---",
        f"write_restart   {cfg.restart_file}",
        "",
    ])

    return "\n".join(lines)


def generate_lammps_input(
    atoms_per_side: int = 10,
    lattice_spacing: float = 5.26,
    potential: str = "lj",
    epsilon: float = 1.0,
    sigma: float = 1.0,
    cutoff: float = 2.5,
    ensemble: str = "nvt",
    temperature: float = 300.0,
    pressure: float = 0.0,
    timestep: float = 0.002,
    n_steps: int = 100000,
    dump_freq: int = 1000,
    minimize: bool = True,
    apply_shear: bool = False,
    shear_rate: float = 0.001,
    shear_direction: str = "xy",
    boundary: str = "p p p",
    output_file: str = "",
) -> str:
    """Generate a complete LAMMPS input script.

    Creates a ready-to-run LAMMPS input file for molecular dynamics simulations.
    Supports LJ, EAM, Tersoff, Buckingham, and Coulomb potentials with
    NVT, NPT, NVE, and NPH ensembles. Optional shear deformation.

    Args:
        atoms_per_side: Number of unit cells per side of the cubic box.
        lattice_spacing: Lattice constant in Angstroms (for LJ: reduced units).
        potential: Type of interatomic potential (lj, eam, tersoff, buckingham, coulomb).
        epsilon: LJ energy parameter (reduced units).
        sigma: LJ length parameter (reduced units).
        cutoff: Cutoff distance for pair interactions.
        ensemble: Thermodynamic ensemble (nvt, npt, nve, nph).
        temperature: Target temperature in Kelvin (or reduced units for LJ).
        pressure: Target pressure in bar (or reduced units for LJ).
        timestep: Timestep in femtoseconds.
        n_steps: Total number of MD steps.
        dump_freq: Frequency of trajectory dumps.
        minimize: Whether to run energy minimization before dynamics.
        apply_shear: Whether to apply shear deformation during dynamics.
        shear_rate: Shear strain rate (1/time).
        shear_direction: Shear plane (xy, xz, or yz).
        boundary: Boundary conditions (e.g. 'p p p').
        output_file: If provided, write the input script to this file.

    Returns:
        The complete LAMMPS input script as a string.
    """
    cfg = LAMMPSInput(
        atoms_per_side=atoms_per_side,
        lattice_spacing=lattice_spacing,
        boundary=boundary,  # type: ignore[arg-type]
        potential=potential,  # type: ignore[arg-type]
        epsilon=epsilon,
        sigma=sigma,
        cutoff=cutoff,
        ensemble=ensemble,  # type: ignore[arg-type]
        temperature=temperature,
        pressure=pressure,
        timestep=timestep,
        n_steps=n_steps,
        dump_freq=dump_freq,
        minimize=minimize,
        apply_shear=apply_shear,
        shear_rate=shear_rate,
        shear_direction=shear_direction,
    )

    buf = io.StringIO()
    buf.write(_build_header(cfg))
    buf.write(_build_init(cfg))
    buf.write(_build_system(cfg))
    buf.write(_build_minimize(cfg))
    buf.write(_build_dynamics(cfg))

    script = buf.getvalue()

    if output_file:
        with open(output_file, "w") as f:
            f.write(script)

    return script


@dataclass
class WorkflowStep:
    """A single step in a LAMMPS workflow."""

    name: str
    n_steps: int
    ensemble: str = "nvt"
    temperature: float = 300.0
    pressure: float = 0.0
    apply_shear: bool = False
    shear_rate: float = 0.001
    dump_freq: int = 100
    thermo_freq: int = 10


@dataclass
class WorkflowConfig:
    """Configuration for a multi-step LAMMPS workflow."""

    atoms_per_side: int = 10
    lattice_spacing: float = 5.26
    potential: str = "lj"
    epsilon: float = 1.0
    sigma: float = 1.0
    cutoff: float = 2.5
    timestep: float = 0.002
    steps: list[WorkflowStep] = field(default_factory=list)

    def __post_init__(self):
        if not self.steps:
            self.steps = [
                WorkflowStep(name="minimize", n_steps=0, ensemble="nve"),
                WorkflowStep(name="equilibrate", n_steps=10000, ensemble="nvt", temperature=300.0),
                WorkflowStep(name="production", n_steps=100000, ensemble="nvt", temperature=300.0),
            ]


def generate_workflow(
    atoms_per_side: int = 10,
    lattice_spacing: float = 5.26,
    potential: str = "lj",
    epsilon: float = 1.0,
    sigma: float = 1.0,
    cutoff: float = 2.5,
    timestep: float = 0.002,
    n_minimize_steps: int = 0,
    n_equilibrate_steps: int = 10000,
    equilibrate_temp: float = 300.0,
    equilibrate_ensemble: str = "nvt",
    n_production_steps: int = 100000,
    production_temp: float = 300.0,
    production_ensemble: str = "nvt",
    production_pressure: float = 0.0,
    apply_shear: bool = False,
    shear_rate: float = 0.001,
    shear_direction: str = "xy",
    dump_freq: int = 100,
    thermo_freq: int = 10,
    output_file: str = "",
) -> str:
    """Generate a multi-step LAMMPS workflow (minimize → equilibrate → production).

    Creates a complete input script with three sequential phases:
    1. Energy minimization (optional)
    2. Equilibration (NVT or NPT)
    3. Production run (with optional shear)

    Args:
        atoms_per_side: Number of unit cells per side.
        lattice_spacing: Lattice constant.
        potential: Interatomic potential type.
        epsilon: LJ energy parameter.
        sigma: LJ length parameter.
        cutoff: Pair potential cutoff.
        timestep: Integration timestep.
        n_minimize_steps: Number of minimization steps (0 to skip).
        n_equilibrate_steps: Number of equilibration steps.
        equilibrate_temp: Temperature for equilibration.
        equilibrate_ensemble: Ensemble for equilibration (nvt, npt).
        n_production_steps: Number of production steps.
        production_temp: Temperature for production.
        production_ensemble: Ensemble for production (nvt, npt).
        production_pressure: Pressure for production (if npt).
        apply_shear: Apply shear during production.
        shear_rate: Shear strain rate.
        shear_direction: Shear plane (xy, xz, yz).
        dump_freq: Dump frequency during production.
        thermo_freq: Thermodynamic output frequency.
        output_file: Optional file path to write the script.

    Returns:
        Complete LAMMPS input script as a string.
    """
    lines = [
        "# SciMCP Multi-Step Workflow",
        "# Phase 1: Minimize  ->  Phase 2: Equilibrate  ->  Phase 3: Production",
        "",
        "# --- Initialization ---",
        "units           lj",
        "dimension       3",
        "boundary        p p p",
        "atom_style      atomic",
        "",
        "# --- System Setup ---",
        f"lattice         fcc {lattice_spacing}",
        f"region          box block 0 {atoms_per_side} 0 {atoms_per_side} 0 {atoms_per_side}",
        "create_box      1 box",
        "create_atoms    1 box",
        "mass            1 1.0",
        "",
        "# --- Pair Potential ---",
    ]

    if potential == "lj":
        lines.extend([
            f"pair_style      lj/cut {cutoff}",
            f"pair_coeff      1 1 {epsilon} {sigma} {cutoff}",
        ])
    elif potential == "eam":
        lines.extend([
            "pair_style      eam/alloy",
            "pair_coeff      1 1 Cu.eam.alloy Cu",
        ])
    elif potential == "tersoff":
        lines.extend([
            "pair_style      tersoff",
            "pair_coeff      1 1 Si.tersoff Si",
        ])

    lines.extend([
        "neighbor        0.3 bin",
        "neigh_modify    delay 0 every 1 check yes",
        "timestep        {:.4f}".format(timestep),
        "",
    ])

    # Phase 1: Minimize
    if n_minimize_steps > 0:
        lines.extend([
            "# ===== PHASE 1: Energy Minimization =====",
            "thermo          100",
            "thermo_style    custom step temp pe ke etotal press",
            "min_style       cg",
            "minimize        1.0e-4 1.0e-6 10000 100000",
            "",
        ])

    # Phase 2: Equilibrate
    lines.extend([
        "# ===== PHASE 2: Equilibration =====",
        f"# {n_equilibrate_steps} steps, {equilibrate_ensemble.upper()}, T={equilibrate_temp}",
        f"thermo          {thermo_freq}",
        f"thermo_style    custom step temp pe ke etotal press vol",
        f"dump            1 all custom 1000 dump.equilibrate.lammpstrj id type x y z vx vy vz",
        f"dump_modify     1 sort id",
    ])

    if equilibrate_ensemble == "nvt":
        lines.append(f"fix             1 all nvt temp {equilibrate_temp} {equilibrate_temp} 0.1")
    elif equilibrate_ensemble == "npt":
        lines.append(f"fix             1 all npt temp {equilibrate_temp} {equilibrate_temp} 0.1 iso 0.0 0.0 1.0")

    lines.extend([
        f"run             {n_equilibrate_steps}",
        "unfix           1",
        "undump          1",
        "",
    ])

    # Phase 3: Production
    lines.extend([
        "# ===== PHASE 3: Production Run =====",
        f"# {n_production_steps} steps, {production_ensemble.upper()}, T={production_temp}",
        f"dump            2 all custom {dump_freq} dump.production.lammpstrj id type x y z vx vy vz",
        f"dump_modify     2 sort id",
    ])

    if production_ensemble == "nvt":
        lines.append(f"fix             2 all nvt temp {production_temp} {production_temp} 0.1")
    elif production_ensemble == "npt":
        lines.append(f"fix             2 all npt temp {production_temp} {production_temp} 0.1 iso {production_pressure} {production_pressure} 1.0")

    if apply_shear:
        if shear_direction == "xy":
            lines.append(f"fix             3 all deform 1 xy erate {shear_rate} units box remap x")
        elif shear_direction == "xz":
            lines.append(f"fix             3 all deform 1 xz erate {shear_rate} units box remap x")
        elif shear_direction == "yz":
            lines.append(f"fix             3 all deform 1 yz erate {shear_rate} units box remap x")

    lines.extend([
        f"run             {n_production_steps}",
        "",
        "# --- Save Restart ---",
        "write_restart   restart.production.lammps",
        "",
    ])

    script = "\n".join(lines)

    if output_file:
        with open(output_file, "w") as f:
            f.write(script)

    return script
