"""Automated shear-rate sweep for LAMMPS simulations.

Generates and manages a series of LAMMPS simulations at different shear rates
to study rheological behavior, shear thinning/thickening, and viscosity.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np


@dataclass
class SweepConfig:
    """Configuration for a shear-rate sweep."""

    shear_rates: list[float] = field(default_factory=lambda: [0.0001, 0.0005, 0.001, 0.005, 0.001])
    atoms_per_side: int = 10
    lattice_spacing: float = 5.26
    potential: str = "lj"
    epsilon: float = 1.0
    sigma: float = 1.0
    cutoff: float = 2.5
    timestep: float = 0.002
    temperature: float = 300.0
    n_equilibrate: int = 10000
    n_production: int = 100000
    dump_freq: int = 1000
    thermo_freq: int = 100
    shear_direction: str = "xy"
    output_dir: str = "shear_sweep"


def generate_sweep_scripts(config: SweepConfig) -> dict[str, str]:
    """Generate LAMMPS input scripts for a shear-rate sweep.

    Creates one input script per shear rate, each performing:
    1. System setup (FCC lattice)
    2. Energy minimization
    3. NVT equilibration
    4. Production run with shear deformation

    Args:
        config: SweepConfig with simulation parameters.

    Returns:
        Dictionary mapping shear_rate (str) to LAMMPS input script content.
    """
    scripts: dict[str, str] = {}

    for rate in config.shear_rates:
        rate_label = f"{rate:.6f}".replace(".", "p").replace("-", "m")

        lines = [
            f"# Shear Rate Sweep — rate = {rate}",
            f"# Generated by SciMCP shear_rate_sweep",
            "",
            "# --- Initialization ---",
            "units           lj",
            "dimension       3",
            "boundary        p p p",
            "atom_style      atomic",
            "",
            "# --- System Setup ---",
            f"lattice         fcc {config.lattice_spacing}",
            f"region          box block 0 {config.atoms_per_side} 0 {config.atoms_per_side} 0 {config.atoms_per_side}",
            "create_box      1 box",
            "create_atoms    1 box",
            "mass            1 1.0",
            "",
            "# --- Pair Potential ---",
            f"pair_style      lj/cut {config.cutoff}",
            f"pair_coeff      1 1 {config.epsilon} {config.sigma} {config.cutoff}",
            f"neighbor        0.3 bin",
            f"neigh_modify    delay 0 every 1 check yes",
            f"timestep        {config.timestep}",
            "",
            "# --- Minimization ---",
            "thermo          100",
            "thermo_style    custom step temp pe ke etotal press",
            "min_style       cg",
            "minimize        1.0e-4 1.0e-6 10000 100000",
            "",
            "# --- Equilibration ---",
            f"fix             1 all nvt temp {config.temperature} {config.temperature} 0.1",
            f"run             {config.n_equilibrate}",
            "unfix           1",
            "",
            "# --- Production with Shear ---",
            f"fix             2 all nvt temp {config.temperature} {config.temperature} 0.1",
            f"fix             3 all deform 1 xy erate {rate} units box remap x",
            f"thermo          {config.thermo_freq}",
            f"thermo_style    custom step temp pe ke etotal press vol lx ly lz xy",
            f"dump            1 all custom {config.dump_freq} dump.shear_{rate_label}.lammpstrj id type x y z vx vy vz",
            "dump_modify     1 sort id",
            f"run             {config.n_production}",
            "",
            "# --- Save ---",
            f"write_restart   restart.shear_{rate_label}.lammps",
            "",
        ]

        scripts[str(rate)] = "\n".join(lines)

    return scripts


def write_sweep_scripts(
    config: SweepConfig,
    output_dir: str = "",
) -> dict[str, str]:
    """Generate and write shear-rate sweep scripts to disk.

    Args:
        config: SweepConfig with simulation parameters.
        output_dir: Directory to write scripts to. If empty, uses config.output_dir.

    Returns:
        Dictionary mapping shear_rate to the file path written.
    """
    if not output_dir:
        output_dir = config.output_dir

    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    scripts = generate_sweep_scripts(config)
    file_map: dict[str, str] = {}

    for rate, script in scripts.items():
        rate_val = float(rate)
        rate_label = f"{rate_val:.6f}".replace(".", "p").replace("-", "m")
        filepath = out_path / f"in.shear_{rate_label}"
        filepath.write_text(script)
        file_map[rate] = str(filepath)

    # Write sweep metadata
    meta = {
        "shear_rates": config.shear_rates,
        "atoms_per_side": config.atoms_per_side,
        "potential": config.potential,
        "temperature": config.temperature,
        "n_equilibrate": config.n_equilibrate,
        "n_production": config.n_production,
        "shear_direction": config.shear_direction,
        "scripts": file_map,
    }
    meta_path = out_path / "sweep_config.json"
    meta_path.write_text(json.dumps(meta, indent=2))
    file_map["config"] = str(meta_path)

    return file_map


def estimate_viscosity(
    shear_rates: np.ndarray,
    shear_stresses: np.ndarray,
) -> dict[str, Any]:
    """Estimate viscosity from shear rate vs shear stress data.

    Fits a power-law model: stress = K * rate^n
    where n=1 is Newtonian, n<1 is shear-thinning, n>1 is shear-thickening.

    Args:
        shear_rates: Array of shear rates.
        shear_stresses: Array of corresponding shear stresses.

    Returns:
        Dictionary with:
        - 'apparent_viscosities': η = stress/rate at each point
        - 'power_law_K': Consistency index K
        - 'power_law_n': Flow behavior index
        - 'is_shear_thinning': True if n < 1
        - 'is_shear_thickening': True if n > 1
        - 'zero_shear_viscosity': Extrapolated viscosity at rate → 0
    """
    rates = np.asarray(shear_rates, dtype=float)
    stresses = np.asarray(shear_stresses, dtype=float)

    # Filter out zero rates
    mask = rates > 0
    rates = rates[mask]
    stresses = stresses[mask]

    # Apparent viscosity
    viscosities = stresses / rates

    # Power-law fit in log space: log(stress) = log(K) + n * log(rate)
    log_rates = np.log(rates)
    log_stresses = np.log(stresses)

    coeffs = np.polyfit(log_rates, log_stresses, 1)
    n = coeffs[0]
    K = np.exp(coeffs[1])

    return {
        "apparent_viscosities": viscosities.tolist(),
        "power_law_K": float(K),
        "power_law_n": float(n),
        "is_shear_thinning": bool(n < 1.0),
        "is_shear_thickening": bool(n > 1.0),
        "zero_shear_viscosity": float(viscosities[0]) if len(viscosities) > 0 else 0.0,
    }


def analyze_sweep_results(
    sweep_dir: str,
) -> dict[str, Any]:
    """Analyze results from a completed shear-rate sweep.

    Reads thermo data from all shear rate directories and computes
    stress vs rate curves and viscosity estimates.

    Args:
        sweep_dir: Path to the sweep output directory.

    Returns:
        Dictionary with per-rate statistics and overall rheological analysis.
    """
    sweep_path = Path(sweep_dir)
    config_file = sweep_path / "sweep_config.json"

    if not config_file.exists():
        raise FileNotFoundError(f"Sweep config not found: {config_file}")

    with open(config_file) as f:
        config = json.load(f)

    results: dict[str, Any] = {"rates": [], "viscosities": [], "pressures": [], "temps": []}

    for rate_str, filepath in config.get("scripts", {}).items():
        if rate_str == "config":
            continue

        rate = float(rate_str)
        # Look for thermo output in the same directory
        thermo_file = sweep_path / f"thermo_{rate_str}.dat"
        if thermo_file.exists():
            try:
                from .parser import parse_thermo_data

                data = parse_thermo_data(str(thermo_file))
                if "Press" in data["columns"]:
                    results["rates"].append(rate)
                    results["pressures"].append(float(np.mean(data["columns"]["Press"][-100:])))
                    if "Temp" in data["columns"]:
                        results["temps"].append(float(np.mean(data["columns"]["Temp"][-100:])))
            except Exception:
                pass

    if results["rates"]:
        results["rates"] = np.array(results["rates"])
        results["pressures"] = np.array(results["pressures"])
        # Viscosity = stress / rate (for shear stress ≈ pressure in LJ units)
        results["viscosities"] = (results["pressures"] / results["rates"]).tolist()

    return results
